services:
  - type: worker
    name: discord-study-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore  # 한국과 가장 가까운 리전
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_CHANNEL_ID
        sync: false
      - key: TZ
        value: Asia/Seoul
    healthCheckPath: /